services:
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin111
      POSTGRES_DB: ad_platform_db
    ports:
      - "5432:5432"
    volumes:
      - ../init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin111
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pgnetwork

  flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - pgnetwork
    volumes:
      - ..:/app
    environment:
      - FLASK_ENV=development

networks:
  pgnetwork:

volumes:
  dbdata:
  pgadmin_data:
